<a href="https://colab.research.google.com/github/Vikash-av/MA-637-NUMERICAL-ANALYSIS-IITGN-/blob/main/Assignment_4_qno_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
def augumented_matrix(A,b):
  augment_matrix= np.zeros((np.size(b),np.size(b)+1))
  for i in range(np.size(b)):
    for j in range(np.size(b)+1):
      if j <= np.size(b) -1:
        augment_matrix[i][j]=A[i][j]
      else:
        augment_matrix[i][j]=b[i]
  return augment_matrix

# Example to check function is correctly defined or not
a= [[1, -1, 1],
    [3, -3, 1],
    [-1, 1, -3]]
m=[4,2,-14]
print(augumented_matrix(a,m))

#now we are checking the pivots
def check_pivot(augment_matrix,n,i):
  p= -1
  for q in range(i,n):
    if (augment_matrix[q][i] != 0):
        p=q
        break
  if p == -1:
      print(f"System has no solution")
      exit()

  if(p!=i):
    temp= 0
    for j in range(n+1):
      temp=augment_matrix[i][j]
      augment_matrix[i][j]=augment_matrix[p][j]
      augment_matrix[p][j]=temp
  return augment_matrix

#now,we are computing values using backward substitution

def backward_substitution(xn, augment_matrix, n):
  xn[n-1]= augment_matrix[n-1][n]/augment_matrix[n-1][n-1]
  for i in range(n-2,-1,-1):
    sum =0
    for j in range(i+1,n):
      sum += augment_matrix[i][j]* xn[j]
    xn[i]=(augment_matrix[i][n] - sum)/augment_matrix[i][i]

  return xn

#c= [[1, 1, 0,1,2],
    #[0, 1, 1,1,3],
    #[0, 0, 0,-3,-3],
    #[0,0,3,3,3]]
#(check_pivot(c,4,2))
d=[[1,-1,3,2],
   [0,2,-3,1],
   [0,0,-8,-7]]
e=[0,0,0]
print(backward_substitution(e,d,3))
f=[[1,1,0,1,2],
   [0,1,1,1,3],
   [0,0,0,0,0],
   [0,0,0,-3,-3]]
g=[0,0,0,0]
#print(backward_substitution(g,f,4))

if __name__== "__main__":
  np.set_printoptions(precision=3,suppress=True)

  A=([1,-1,2,-1],
     [2,-2,3,-1],
     [1,1,1,0],
     [1,-1,4,3])
  b=[-8,-20,-2,4]
  n=np.size(b)

#Augment matrix [A:b]  #to check after this

  augment_matrix=np.zeros((np.size(b),np.size(b)+1))
  augment_matrix= augumented_matrix(A,b)
  print(f"A(1) : \n {augment_matrix}")

  for i in range(n-1):
    augment_matrix=check_pivot(augment_matrix,n,i)
    m_ki= 0.0
    for k in range(i+1,n):
      m_ki=augment_matrix[k][i]/augment_matrix[i][i]
      for j in range(i,n+1):
        augment_matrix[k][j]=augment_matrix[k][j]-m_ki * (augment_matrix[i][j])

    print(f"A({i+2}) : \n {augment_matrix}")

#now,we are checking Ann is zero or not

  if (augment_matrix[n-1][n-1] == 0):
    print("System has no unique solution")
    exit()

 #Backward Substitution

  xn=np.zeros((np.size(b)))
  xn=backward_substitution(xn,augment_matrix,n)
  print(f"The solution of the system : {xn}")

  error = 0
  x=[-7,3,2,2]

  error=np.linalg.norm(x-xn, ord =2)
  print(f"The error : {error}")


 ##################################################################

  A_1=([1,2,3,4],
       [2,5,8,10],              #we can change 10 to 1 to get solution
       [3,8,14,16],
       [4,10,16,20])
  b=[-8,-20,-2,4]

  augment_matrix=np.zeros((np.size(b),np.size(b)+1))
  augment_matrix= augumented_matrix(A_1,b)
  print(f"A(1) : \n {augment_matrix}")

  for i in range(n-1):
    augment_matrix=check_pivot(augment_matrix,n,i)
    m_ki= 0.0
    for k in range(i+1,n):
      m_ki=augment_matrix[k][i]/augment_matrix[i][i]
      for j in range(i,n+1):
        augment_matrix[k][j]=augment_matrix[k][j]-m_ki * (augment_matrix[i][j])

    print(f"A_1({i+2}) : \n {augment_matrix}")

#now,we are checking Ann is zero or not

  if (augment_matrix[n-1][n-1] == 0):
    print("System has no unique solution")
    exit()

 #Backward Substitution

  xn=np.zeros((np.size(b)))
  xn=backward_substitution(xn,augment_matrix,n)
  print(f"The solution of the system : {xn}")









[[  1.  -1.   1.   4.]
 [  3.  -3.   1.   2.]
 [ -1.   1.  -3. -14.]]
[1.1875, 1.8125, 0.875]
A(1) : 
 [[  1.  -1.   2.  -1.  -8.]
 [  2.  -2.   3.  -1. -20.]
 [  1.   1.   1.   0.  -2.]
 [  1.  -1.   4.   3.   4.]]
A(2) : 
 [[ 1. -1.  2. -1. -8.]
 [ 0.  0. -1.  1. -4.]
 [ 0.  2. -1.  1.  6.]
 [ 0.  0.  2.  4. 12.]]
A(3) : 
 [[ 1. -1.  2. -1. -8.]
 [ 0.  2. -1.  1.  6.]
 [ 0.  0. -1.  1. -4.]
 [ 0.  0.  2.  4. 12.]]
A(4) : 
 [[ 1. -1.  2. -1. -8.]
 [ 0.  2. -1.  1.  6.]
 [ 0.  0. -1.  1. -4.]
 [ 0.  0.  0.  6.  4.]]
The solution of the system : [-11.667   5.      4.667   0.667]
The error : 5.8878405775518985
A(1) : 
 [[  1.   2.   3.   4.  -8.]
 [  2.   5.   8.   1. -20.]
 [  3.   8.  14.  16.  -2.]
 [  4.  10.  16.  20.   4.]]
A_1(2) : 
 [[ 1.  2.  3.  4. -8.]
 [ 0.  1.  2. -7. -4.]
 [ 0.  2.  5.  4. 22.]
 [ 0.  2.  4.  4. 36.]]
A_1(3) : 
 [[ 1.  2.  3.  4. -8.]
 [ 0.  1.  2. -7. -4.]
 [ 0.  0.  1. 18. 30.]
 [ 0.  0.  0. 18. 44.]]
A_1(4) : 
 [[ 1.  2.  3.  4. -8.]
 [ 0.  1.  2. -7. -4