<a href="https://colab.research.google.com/github/Vikash-av/MA-637-NUMERICAL-ANALYSIS-IITGN-/blob/main/Assignment_5(qno4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# function to check matrix is symmetric or not
def check_symmetric(A):
  n=np.shape(A)[0]                       #if a matrix is of size n*n it will give n basically returns no of rows of the matrix
  check = 0
  for i in range(n):
    for j in range(n):
      if j > i:                          # to check only upper triangle
       if A[i][j] != A[j][i]:
         check +=1
         break
  if (check ==0):
    return True
  else:
    return False

#a=[[1,2,3],
   #[56,4,6],
   #[3,6,7]]
#print(check_symmetric(a))

#function to compute values using forward substitution
def forward_substitution(matrix, rhs, n):
  xn = np.zeros(n)
  xn[0] = rhs[0]/matrix[0][0]
  for i in range(1,n):
    sum = 0
    for j in range(i):
      sum += matrix[i][j] * xn[j]
    xn[i] = (rhs[i] - sum) / matrix[i][i]
  return xn

#b=[[1,0,0],
   #[-0.5,1,0],
   #[0,-0.667,1]]
#c=[1,0,0]
#n=3
#print(forward_substitution(b,c,n))

#function to compute values using backward substituion

def backward_substitution(matrix, rhs, n):
  xn = np.zeros(n)
  xn[n-1]= rhs[n-1] / matrix[n-1][n-1]
  for i in range(n-2, -1, -1):
    sum = 0
    for j in range(i+1, n):
      sum += matrix[i][j] * xn[j]
    xn[i] = (rhs[i] - sum) / xn[j]    #matrix[i][i]
  return xn

d= [[1,-0.5,0],
    [0,1,-0.667],
    [0,0,1]]
e=[0.5, 0.333, 1]
print(backward_substitution(d,e,3))

if __name__ == "__main__":
  A = np.array ([[4, 0, 2, 1], [0, 3, -1, 1], [2, -1, 6, 3],[1, 1, 3, 8]])
  b = np.array([-8, -20, -2, 4])
  print(f"A : \n{A}")
  matrix_symmetric = check_symmetric(A)
  if matrix_symmetric == True:
    print(f"Matrix is Symmetric")
  else:
    print(f"Matrix is not symmetric, cannot do LDL decomposition!")
    exit()

  n = np.shape(A)[0]

#now, creating L and D matrix of the same size as the identity.

  L = np.identity(n)
  D = np.identity(n)
  D[0][0] = A[0][0]
  for i in range(n):
    if i != 0:
      intermediate = 0
      sum = 0
      for j in range(i):
         sum += (L[i][j])**2 * D[j][j]                                     #(*)
      D[i][i] = A[i][i] - sum
    for j in range(i+1,n):
      sum = 0
      for k in range(i):
        sum += L[i][k] * L[j][k] * D[k][k]
      L[j][i] = (A[j][i] - sum )/ D[i][i]

  print(f"L  : \n{L}")
  print(f"D  : \n{D}")

#checking LDL^T = A or not

  print(f"CA : \n{np.dot(np.dot (L,D), np.transpose(L))}")

  #solving Ly=b
  y = np.zeros(n)
  y=np.linalg.solve(L,b)         #to change y = backward_substiturion(L,b,n)
  #print(y)

  #solving Dz=y
  #Z_2 = np.zeros(n)
  #z_2= np.linalg.solve(D,y)
  #print(z_2)

  z = np.zeros(n)
  for i in range(n):
    z[i] = y[i] / D[i][i]

  #print(z)

  #solving L^tx = z

  #x = np.zeros(n)
  #x = np.linalg.solve(np.transpose(L) , z)
  #print(x)
  L_t = np.transpose(L)
  x = forward_substitution(L_t,z,n)
  #Solution

  print(f"Solution x : {x}")

  #4(b)

  P = np.array([[1,2,3],[2,3,8],[1,8,4]])


  #checking matrix P is symmetric or not
  print(f"P: \n{P}")
  if (check_symmetric(P) == True):
    print(f" Matrix is Symmetric")
  else:
    print(f" Matrix is not Symmetric")

  #4(c)

  #computing D^(1/2)

  sqrt_D = np.diag(np.sqrt(np.diag(D)))
  print(f" D^(1/2) : \n{sqrt_D}")

  L_cap = np.dot(L,sqrt_D)
  print(f" L_cap = LD^(1/2): \n{L_cap}")
  print(f"L_cap transpose is :\n{np.transpose(L_cap)}")





[1. 1. 1.]
A : 
[[ 4  0  2  1]
 [ 0  3 -1  1]
 [ 2 -1  6  3]
 [ 1  1  3  8]]
Matrix is Symmetric
L  : 
[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.5        -0.33333333  1.          0.        ]
 [ 0.25        0.33333333  0.60714286  1.        ]]
D  : 
[[4.         0.         0.         0.        ]
 [0.         3.         0.         0.        ]
 [0.         0.         4.66666667 0.        ]
 [0.         0.         0.         5.69642857]]
CA : 
[[ 4.  0.  2.  1.]
 [ 0.  3. -1.  1.]
 [ 2. -1.  6.  3.]
 [ 1.  1.  3.  8.]]
Solution x : [-2.         -6.66666667 -1.          2.72100313]
P: 
[[1 2 3]
 [2 3 8]
 [1 8 4]]
 Matrix is not Symmetric
 D^(1/2) : 
[[2.         0.         0.         0.        ]
 [0.         1.73205081 0.         0.        ]
 [0.         0.         2.1602469  0.        ]
 [0.         0.         0.         2.38671921]]
 L_cap = LD^(1/2): 
[[ 2.          0.          0.          0.        ]
 [ 0.          1.73205