<a href="https://colab.research.google.com/github/Vikash-av/MA-637-NUMERICAL-ANALYSIS-IITGN-/blob/main/Assignment_6(qno4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#we will first compute the omega used in the sor iterative method

def optimal_omega(A):
  omega = 0.0
  n = np.shape(A)[0]
  L = np.zeros((n,n))
  D = np.zeros((n,n))
  U = np.zeros((n,n))

  #Now, Computing matrix L, D, and U

  for i in range(n):
    for j in range(n):
      if ( i < j):
        U[i][j] = -A[i][j]
      elif i > j:
        L[i][j] == -A[i][j]
      else:
        D[i][j] = A[i][j]

  T = np.zeros ((n,n))

  #iteration matrix for jacobi method

  T = np.dot(np.linalg.inv(D), (L+U))   #(have some doubts)

  #now, computing all eigenvalues

  eigenvalue = np.linalg.eigvalsh(T)

  #abs_eigenvalue = np.abs(eigenvalue)

  #spectral_radius = max(abs_eigenvalue)
  spectral_radius = np.abs(eigenvalue[np.size(eigenvalue)-1])

  omega = 2 / (1 + np.sqrt(1 - spectral_radius**2))

  return omega

if __name__ == "__main__":

  #creating matrix A

  #A = np.array([[10, -1, 2, 0], [-1, 11, -1, 3], [2, -1, 10, -1], [0, 3, -1, 8]])
  A = np.array([[4,3,0], [3,4,-1], [0,-1,4]])
  #b = np.array([6, 25, -11, 15])
  b = np.array([1, 2, 0])

  #choose, Jacobi, SOR, GS
  method = "SOR"

  maximum_iteration = 100
  tolerance = 1e-10
  omega = optimal_omega(A)                       # changing omega
  print(f"Choosen Method  : {method}")
  print(f"Maximum Iteration : {maximum_iteration}")
  print(f"Tolerance : {tolerance}")

  if (method == "SOR"):
    print(f"Omega for SOR : {omega}")

  if (method == "GS"):
    omega = 1

  #Dimension
  n = np.shape(A)[0]
  x = np.zeros(n)

  # Initial iterate is set to zero. We call it old_iterate as we copy these values
  # for the next iterative process.
  old_iterate = np.zeros(n)

  # Loop over the maximum number of iteration

  for iterate in range(maximum_iteration):
    # SOR iteration

    for i in range(n):
      sum = b[i]
      for j in range(n):
        if method == "jacobi":
          if i != j:
            sum -= A[i][j] * old_iterate[j]
        elif method == "SOR" or method == "GS":
          if j < i :
            sum -= A[i][j] * x[j]
          elif i < j :
            sum -= A[i][j] * old_iterate[j]

          else:
            print(f"Method Unknown : {method}")
            exit()

    # Update the value of xi
    x[i] = (1 - omega) * old_iterate[i] + omega * (sum/ A[i][i])
    # Compute the error between the successive iteration steps. We are using the
    # l_inf norm.

    error = np.linalg.norm(x - old_iterate, ord=np.inf)
    if error < tolerance:
      print(f"Solution :{x}")
      print(f"Convergence reached with {iterate+1} number of iterations ")
      break

    # Copy the old solution vector
    # NOTE: If we use old_iterate = x, then it is incorrect as it's not copying but a new
    #       reference to the old variable.

    old_iterate = np.copy(x)
    # In Python you can use a else with a for loop, in the case maximum number of iteration
    # is reached, i.e., the code doesn't break, then we execute the else part
  else:
        print(f"Maximum iterations reached without Convergence")


##################################################################
  #choose, Jacobi, SOR, GS
  method = "jacobi"

  maximum_iteration = 100
  tolerance = 1e-10
  omega = optimal_omega(A)                       # changing omega
  print(f"Choosen Method  : {method}")
  print(f"Maximum Iteration : {maximum_iteration}")
  print(f"Tolerance : {tolerance}")

  if (method == "SOR"):
    print(f"Omega for SOR : {omega}")

  if (method == "GS"):
    omega = 1

  #Dimension
  n = np.shape(A)[0]
  x = np.zeros(n)

  # Initial iterate is set to zero. We call it old_iterate as we copy these values
  # for the next iterative process.
  old_iterate = np.zeros(n)

  # Loop over the maximum number of iteration

  for iterate in range(maximum_iteration):
    # SOR iteration

    for i in range(n):
      sum = b[i]
      for j in range(n):
        if method == "jacobi":
          if i != j:
            sum -= A[i][j] * old_iterate[j]
        elif method == "SOR" or method == "GS":
          if j < i :
            sum -= A[i][j] * x[j]
          elif i < j :
            sum -= A[i][j] * old_iterate[j]

          else:
            print(f"Method Unknown : {method}")
            exit()

    # Update the value of xi
    x[i] = (1 - omega) * old_iterate[i] + omega * (sum/ A[i][i])
    # Compute the error between the successive iteration steps. We are using the
    # l_inf norm.

    error = np.linalg.norm(x - old_iterate, ord=np.inf)
    if error < tolerance:
      print(f"Solution :{x}")
      print(f"Convergence reached with {iterate+1} number of iterations ")
      break

    # Copy the old solution vector
    # NOTE: If we use old_iterate = x, then it is incorrect as it's not copying but a new
    #       reference to the old variable.

    old_iterate = np.copy(x)
    # In Python you can use a else with a for loop, in the case maximum number of iteration
    # is reached, i.e., the code doesn't break, then we execute the else part
  else:
        print(f"Maximum iterations reached without Convergence")












Choosen Method  : SOR
Maximum Iteration : 100
Tolerance : 1e-10
Omega for SOR : 1.0
Method Unknown : SOR
Method Unknown : SOR
Method Unknown : SOR
Solution :[0. 0. 0.]
Convergence reached with 1 number of iterations 
Choosen Method  : jacobi
Maximum Iteration : 100
Tolerance : 1e-10
Solution :[0. 0. 0.]
Convergence reached with 1 number of iterations 


In [ ]:
import numpy as np
n=5
b=np.zeros(n)
c=np.zeros((n,n))
print(b)
print(c)
e=[[-8,0],
   [0,-4]]
f = [[5,6],
     [8,9]]
print(np.add(e,f))
print(np.linalg.inv(e))
print(np.linalg.eigvalsh(e))
eigen=(np.linalg.eigvalsh(e))
sr = max(np.abs(eigen))
print(sr)
print(1e-10 - 1e-10)


[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[-3  6]
 [ 8  5]]
[[-0.125 -0.   ]
 [-0.    -0.25 ]]
[-8. -4.]
8.0
0.0


In [ ]:
import numpy as np

# Compute the Optimal Omega used in SOR iteration
def optimal_omega(A):
    omega = 0.0
    n = np.shape(A)[0]
    # The matrices L, D, and U
    # FITB
    L = np.zeros((n,n))
    D = np.zeros((n,n))
    U = np.zeros((n,n))
    # Computation of the matrices L, D, and U
    # FITB
    for i in range(n):
        for j in range(n):
            if i<j:
                U[i][j] = -A[i][j]
            elif i>j:
                L[i][j] = -A[i][j]
            else:
                D[i][j] = A[i][j]
    T = np.zeros((n,n))
    # Iteration matrix for Jacobi method
    # FITB
    T = np.dot(np.linalg.inv(D), (L+U))
    # Compute all the eigenvalues
    eigenvalue = np.linalg.eigvals(T)
    # Maximum eigenvalue
    # FITB
    spectral_radius = np.abs(eigenvalue[np.size(eigenvalue)-1])

    # Optimal omega for SOR
    # FITB
    omega = 2/(1+np.sqrt(1-spectral_radius**2))

    return omega

if __name__ == "__main__":
    # Create matrix A
    #A = np.array([[10, -1, 2, 0], [-1, 11, -1, 3], [2, -1, 10, -1], [0, 3, -1, 8]])
    A = np.array([[4,3,0], [3,4,-1], [0,-1,4]])
    #b = np.array([6, 25, -11, 15])
    b = np.array([1, 2, 0])

    # Choose Jacobi, SOR, GS (Gauss Seidel)
    method = "SOR"
    # Maximum number of iteration and tolerance
    max_iteration = 100
    tolerance = 1e-10
    omega = optimal_omega(A)
    print(f"Chosen Method     : {method}")
    print(f"Maximum Iteration : {max_iteration}")
    print(f"Tolerance         : {tolerance}")
    if method == "SOR":
        print(f"Omega for SOR     : {omega}")

    if method == "GS":  ## or method == Jacobi
        # Set omega = ? for Gauss Seidel
        # FITB
        omega = 1

    # Dimension
    n = np.shape(A)[0]
    x = np.zeros(n)

    # Initial iterate is set to zero. We call it old_iterate as we copy these values
    # for the next iterative process.
    old_iterate = np.zeros(n)

    # Loop over the maximum number of iteration
    for iterate in range(max_iteration):
        # SOR iteration
        for i in range(n):
            # FITB
            sum = b[i]
            for j in range(n):
                if method == "Jacobi":
                    if i!=j:
                        sum -= A[i][j]*old_iterate[j]  # FITB
                elif method == "SOR" or method == "GS":
                    if j<i:
                        sum -= A[i][j]*x[j]   # FITB
                    elif i<j:
                        sum -= A[i][j]*old_iterate[j]   # FITB
                else:
                    print(f"Method Unknown : {method}")
                    exit()

            # Update the values of x_i
            # FITB
            x[i] = (1-omega)*old_iterate[i] + omega*(sum/A[i][i])

        # Compute the error between the successive iteration steps. We are using the
        # l_inf norm.
        # FITB
        error = np.linalg.norm(x-old_iterate)
        if error < tolerance:
            print(f"Solution          : {x}")
            print(f"Convergence reached with {iterate+1} number of iterations")
            break

        # Copy the old solution vector
        # NOTE: If we use old_iterate = x, then it is incorrect as it's not copying but a new
        #       reference to the old variable.
        old_iterate = np.copy(x)
    # In Python you can use a else with a for loop, in the case maximum number of iteration
    # is reached, i.e., the code doesn't break, then we execute the else part
    else:
        print(f"Maimum iterations reached without Convergence")

Chosen Method     : SOR
Maximum Iteration : 100
Tolerance         : 1e-10
Omega for SOR     : 1.0
Solution          : [-0.375       0.83333333  0.20833333]
Convergence reached with 49 number of iterations
